# This file was generated by GoReleaser. DO NOT EDIT.
cask "bun-cli" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "dbe4ed7adf096b2430d9a9161b18874f46af3583fe23f0fc1ecff8fcf9407c58"
      url "https://github.com/AtomiCloud/diene.bun-cli/releases/download/v#{version}/bun-cli_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a0eae5269629262cf3bd0d157720bd24b38efa0f3d7facec3c2542e81a06df03"
      url "https://github.com/AtomiCloud/diene.bun-cli/releases/download/v#{version}/bun-cli_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "777ebd5b6e4079c0467b6e9db487653044e8f352bc37b7d602eafbbd9262f227"
      url "https://github.com/AtomiCloud/diene.bun-cli/releases/download/v#{version}/bun-cli_linux_arm64.tar.gz"
    end
  end

  name "bun-cli"
  desc "Sample CLI baseline over the AtomiCloud Redis key-value library"
  homepage "https://github.com/AtomiCloud/diene.bun-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bun-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bun-cli"]
    end
  end

  # No zap stanza required

end
