# This file was generated by GoReleaser. DO NOT EDIT.
cask "cyanprint" do
  version "4.6.0"

  on_macos do
    on_intel do
      sha256 "35d25110ca2774e73d724bb15b9ae85d39e2de32581613e9408a03c04265b9e0"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7030f4966c42cd45a50129272299fd29116b65a94a4de05790506e607aaed9b4"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d797ff1a85020439aa8e0cb2f2d2b1982c53610c11f5cb4cad268aa57d85983c"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "99fdb40da4b308a29a5fc615c9a487ae5d8b28f646fb04ff7b5f687620f89519"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cyanprint"
  desc "CyanPrint v4 local-first template runtime"
  homepage "https://cyanprint.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cyanprint"

  # No zap stanza required

end
