# This file was generated by GoReleaser. DO NOT EDIT.
cask "cyanprint" do
  version "4.4.0"

  on_macos do
    on_intel do
      sha256 "384a6e6a58e5d2811b71b7f128b47f4dc3e7839f7a6b48e13b9e7d95c665bf5b"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "35a754aebec6802170ecde86dc5990ee6057899bb1a7ed1b14983b8fbc902d0d"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "592ebb07c2e174d47f9727bde52b2456ebb17c6a22b93a853f1f862793845b2e"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2c8845fe49201400d2ca3981cafd27d2ed4b33005b0f6a0073b2e005b2dc552d"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cyanprint"
  desc "CyanPrint v4 local-first template runtime"
  homepage "https://cyanprint.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cyanprint"

  # No zap stanza required

end
