# This file was generated by GoReleaser. DO NOT EDIT.
cask "cyanprint" do
  version "4.7.0"

  on_macos do
    on_intel do
      sha256 "7c41152983fc55a1eedf5065f8222c32f0c579345a0ff633fb44a4c16a6c6b57"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "603325d2b650c027e0e1a05181177f706c101df91672ca7f686b3d663c009a0a"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1b830a489b6c12078a75c30ffec6bb576da235fedd85c68208840aa82f10028f"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "70435af2ff12e7e8b2de6df6813bb0c69aa8dfc39ab14fd29529199d8aa5946a"
      url "https://github.com/AtomiCloud/sulfone.lite/releases/download/v#{version}/cyanprint_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cyanprint"
  desc "CyanPrint v4 local-first template runtime"
  homepage "https://cyanprint.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cyanprint"

  # No zap stanza required

end
